import 'package:LAST_SUMMER_COFFE/model/urun_model.dart';

class Urunler {
  List<Urun> urunler = [
    Urun(urunAdi: "Çay", fiyat: 7.50, adet: 1),
    Urun(urunAdi: "Su", fiyat: 7.50, adet: 1),
    Urun(urunAdi: "Oralet Çeşitleri", fiyat: 10.00, adet: 1),
    Urun(urunAdi: "Fincan Nescafe", fiyat: 20.00, adet: 1),
    Urun(urunAdi: "Bardak Nescafe", fiyat: 10.00, adet: 1),
    Urun(urunAdi: "Bitki Çayı", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Menengiç Kahvesi", fiyat: 25.00, adet: 1),
    Urun(urunAdi: "Expresso", fiyat: 50.00, adet: 1),
    Urun(urunAdi: "Americano", fiyat: 50.00, adet: 1),
    Urun(urunAdi: "Caramel Latte", fiyat: 60.00, adet: 1),
    Urun(urunAdi: "Sahlep", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Dibek Kahvesi", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Türk Kahvesi", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Sıcak Çikolata", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Meyve Suyu", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Meyveli Soda", fiyat: 15.00, adet: 1),
    Urun(urunAdi: "Limonata", fiyat: 15.00, adet: 1),
    Urun(urunAdi: "Sade Soda", fiyat: 10.00, adet: 1),
    Urun(urunAdi: "Cam Kola", fiyat: 25.00, adet: 1),
    Urun(urunAdi: "Gazoz", fiyat: 20.00, adet: 1),
    Urun(urunAdi: "Kutu Kola", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Soğuk Çay", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Red Bull", fiyat: 40.00, adet: 1),
    Urun(urunAdi: "Meyveli Süt", fiyat: 15.00, adet: 1),
    Urun(urunAdi: "Churchill", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Cool Lime", fiyat: 35.00, adet: 1),
    Urun(urunAdi: "Kek", fiyat: 10.00, adet: 1),
    Urun(urunAdi: "Çikolata", fiyat: 15.00, adet: 1),
    Urun(urunAdi: "Kruvasan", fiyat: 30.00, adet: 1),
    Urun(urunAdi: "Tost", fiyat: 50.00, adet: 1),
    Urun(urunAdi: "Tost Menü", fiyat: 80.00, adet: 1),
    Urun(urunAdi: "Gözleme", fiyat: 50.00, adet: 1),
    Urun(urunAdi: "Çerez", fiyat: 50.00, adet: 1),
    Urun(urunAdi: "Kızartma Büyük", fiyat: 80.00, adet: 1),
    Urun(urunAdi: "Kızartma Küçük", fiyat: 40.00, adet: 1),
  ];
}
